# Generated by Django 4.2.3 on 2023-07-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='symptoms',
            new_name='treatment_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='bp_1d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='bp_1s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='bp_2d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='bp_2s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='cholesterol_level',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='glyhb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='hdl',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stab_glu',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_lb',
            field=models.IntegerField(default=0),
        ),
    ]
