# Generated by Django 4.2.3 on 2023-07-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0002_rename_symptoms_patient_treatment_type_patient_bp_1d_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
    ]
