# Generated by Django 4.2.3 on 2023-07-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0004_alter_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='mobile',
        ),
    ]
