# Generated by Django 4.2.3 on 2023-07-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0005_remove_doctor_address_remove_doctor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bp_1d',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bp_1s',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bp_2d',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bp_2s',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glyhb',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight_lb',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
