# Generated by Django 4.2.3 on 2023-07-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0006_alter_patient_bp_1d_alter_patient_bp_1s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bp_1d',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_2d',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bp_2s',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='glyhb',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hdl',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stab_glu',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Endocrinologist', 'Endocrinologist'), ('Cardiologist', 'Cardiologist')], default='Endocrinologist', max_length=50),
        ),
    ]
