# Generated by Django 4.2.3 on 2023-08-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0009_patient_key_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='key',
            new_name='decryption',
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_updated',
            field=models.TextField(blank=True, default=''),
        ),
    ]
